### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by bwanaaa** [happynear/py-leveldb-windows#13]
Using Visual Studio 2019 on windows 10

I opened the solution and under Project selected 'Retarget solution' because my tools are much newer.
I opened the project and found two subprojects:

leveldb (Visual Studio 2015)
leveldb_ext (Visual Studio 2015)

I modified the python path in the settings (Additional Include Directories, Additional Library Directories, Additional Dependencies) in this way:
In the properties panel of leveldb:
    under C/C++-> General-> Additional Include Directories I added C:\Users\Me\Anaconda3\libs
     under Librarian-> General-> Additional Library Directories I added C:\Users\Me\Anaconda3\libs
n the properties panel of leveldb_ext:
    under C/C++-> General-> Additional Include Directories I added C:\Users\Me\Anaconda3\libs
     under Linker-> General-> Input -> Additional Dependencies I added C:\Users\Me\Anaconda3\libs

Fatal error LNK1181 Cannot open input file python27.lib

In the entire solution there are no references to python 27.lib
My Anaconda3 uses python 3.6 and there is no python 2 available. How can I fix this code?

**Comment by bwanaaa** [comment]
I deleted the python27 in the include directory and that fixed the above problem. However now I get the error:

LNK 2001 unresolved external symbol initleveldb

How do I fix this?

**Comment by CryptoCoinLab** [comment]
You should add the directory of python36 and link to the python3.lib.

**Comment by bwanaaa** [comment]
thank you.
