### ISSUE TITLE
I'm such a rookie Anybody can expounds the step 2 ? thanks!

### ISSUE THREAD

**Issue by RussiaVk** [happynear/py-leveldb-windows#16]
`Modify the python path in the settings (Additional Include Directories, Additional Library Directories, Additional Dependencies).

`

**Comment by RussiaVk** [comment]
`Modify the python path in the settings (Additional Include Directories, Additional Library Directories, Additional Dependencies).

`

**Comment by roblee357** [comment]
I'm also curious about this. Also, what does it mean to compile with Python3. Will python create a new .pyd file from the process?
