### ISSUE TITLE
identifier '_BitScanReverse' '_BitScanForward' '_BitScanForward64` is undefined

### ISSUE THREAD

**Issue by smpdev456** [happynear/py-leveldb-windows#7]
Hi 

I want to compile with VS 2017 in Release x64 and Debug x64 mode, but leveldb project failed and report these errors:
identifier "_BitScanReverse" is undefined file:snappy-stubs-internal.h	line:351 project:leveldb	
identifier "_BitScanForward" is undefined file:snappy-stubs-internal.h	 line:356 project:leveldb	
identifier "_BitScanForward64" is undefined file:snappy-stubs-internal.h line:363 project:leveldb	

Thanks

**Comment by PineLover** [comment]
#include <intrin.h>
