### ISSUE TITLE
AttributeError: module 'leveldb' has no attribute 'LevelDB'

### ISSUE THREAD

**Issue by andyoknen** [happynear/py-leveldb-windows#8]
I download binary, place to <python37_path>/Lib/site-packages/leveldb.pyd
Launch test app:
```
import leveldb
db = leveldb.LevelDB('./db')
...
```
and receive error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: Не найден указанный модуль.
```

It is also impossible to compile from source [https://github.com/happynear/py-leveldb-windows/issues/3](url)

**Comment by litvinovivan** [comment]
The file is for Python 3.6. I had the same error with Python 3.7. Downgraded to Python 3.6 and it works fine now.

**Comment by andyoknen** [comment]
Its not actual now, but thanks you:) Information is useful in any case.
